name: app
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: 3.32.8

resolution: workspace

dependencies:
  app_logger:
    path: ../packages/app_logger
  app_preferences:
    path: ../packages/app_preferences
  cached_network_image: ^3.4.1
  cores:
    path: ../packages/cores
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.0.0
  go_router: ^16.0.0
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  slang: ^4.7.2
  slang_flutter: ^4.7.0
  talker_flutter: ^4.9.2
  talker_riverpod_logger: ^4.9.2
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.5.3
  custom_lint: ^0.7.5
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  freezed_lint: ^0.0.9
  go_router_builder: ^3.0.1
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  slang_build_runner: ^4.7.0
  yumemi_lints: ^4.1.1

# NOTE: This is a workaround to fix the build issue. build_runner 2.5.3 is not compatible with build 2.5.3.
dependency_overrides:
  build: ^2.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/music.json
    - assets/event.json
    - assets/stage.json
